import { icons } from 'lucide';
import './style.css';
import './fonts.css';
import './all1.css';

const featured = ['Activity','Airplay','AlarmClock','Aperture','Archive','ArrowDown','ArrowUpRight','Atom','Award','BadgeCheck','Bell','Bike','Bird','Bluetooth','Bolt','BookOpen','Bot','Box','Briefcase','Brush','Calendar','Camera','ChartNoAxesCombined','Check','CircleHelp','Cloud','Code2','Coffee','Compass','Copy','Cpu','Crown','Diamond','Download','Droplets','Eye','Feather','FileText','Flag','Flame','Folder','Gamepad2','Gauge','Gem','Gift','Globe2','Heart','Home','Image','KeyRound','Laptop','Layers','Lightbulb','Link','Lock','Mail','Map','MessageCircle','Mic','Moon','MousePointer2','Music2','Package','Palette','PenTool','Phone','Plane','Play','Plus','Rocket','Search','Send','Settings2','Shield','Sparkles','Star','Sun','Terminal','ThumbsUp','Timer','TrainFront','Trash2','Trophy','Upload','UserRound','Volume2','WandSparkles','Wifi','Zap'];
const categories = { All: featured, Communication:['Mail','MessageCircle','Phone','Mic','Send','Wifi'], Media:['Camera','Image','Music2','Play','Volume2','Airplay'], Objects:['Archive','Box','Briefcase','Coffee','Folder','Package'], Nature:['Bird','Cloud','Droplets','Feather','Flame','Moon','Sun'], System:['Activity','Bell','Bluetooth','Cpu','KeyRound','Lock','Settings2','Terminal'] };
let selected = 'Sparkles', query = '', category = 'All', stroke = 1.8, color = '#7057ff', size = 512, animation = 'None', favorites = JSON.parse(localStorage.getItem('symbol-studio-favorites') || '[]');
const svg = (name, opts={}) => { const I=icons[name] || icons.CircleHelp; return I({width:opts.width||48,height:opts.height||48,strokeWidth:opts.strokeWidth||stroke,color:opts.color||color, ...opts}).outerHTML };
function render(){ const names = categories[category].filter(n=>n.toLowerCase().includes(query.toLowerCase())); const isFav=favorites.includes(selected); document.querySelector('#app').innerHTML=`
 <aside><div class="brand"><span>✦</span> Symbol Studio</div><button class="new" id="random">✦ Surprise me</button><nav>${Object.keys(categories).map(c=>`<button class="nav ${c===category?'active':''}" data-cat="${c}">${c}<em>${categories[c].length}</em></button>`).join('')}</nav><div class="aside-foot">Open icon library<br><small>Built with Lucide · ISC License</small></div></aside>
 <main><header><div><h1>Icon library</h1><p>${featured.length} open-source symbols · export-ready</p></div><label class="search">⌕ <input autofocus placeholder="Search symbols" value="${query}"/><kbd>⌘ K</kbd></label></header><section class="grid">${names.map(n=>`<button class="tile ${n===selected?'selected':''}" data-symbol="${n}"><span class="${n===selected&&animation!=='None'?'animate '+animation:''}">${svg(n,{width:32,height:32})}</span><b>${n.replace(/([A-Z])/g,' $1').trim()}</b>${favorites.includes(n)?'<i>★</i>':''}</button>`).join('') || '<div class="empty">No symbols match that search.</div>'}</section></main>
 <section class="inspector"><div class="preview ${animation!=='None'?'animate '+animation:''}">${svg(selected,{width:120,height:120})}</div><div class="title-row"><div><h2>${selected.replace(/([A-Z])/g,' $1').trim()}</h2><code>lucide:${selected}</code></div><button class="heart" id="favorite">${isFav?'★':'☆'}</button></div><div class="group"><label>Color <output>${color}</output></label><div class="colors">${['#7057ff','#f05281','#ff9b50','#f7cf55','#40b98d','#4a9ee9','#22252e'].map(c=>`<button class="swatch ${c===color?'on':''}" data-color="${c}" style="background:${c}"></button>`).join('')}<input id="picker" type="color" value="${color}"/></div></div><div class="group"><label>Stroke width <output>${stroke}px</output></label><input id="stroke" type="range" min="1" max="3" step=".2" value="${stroke}"/></div><div class="group"><label>Animation <output>${animation}</output></label><div class="segments">${['None','Pulse','Float','Spin'].map(a=>`<button data-animation="${a}" class="${a===animation?'on':''}">${a}</button>`).join('')}</div></div><div class="group"><label>Export size <output>${size} × ${size}</output></label><input id="size" type="range" min="64" max="2048" step="64" value="${size}"/></div><div class="export"><button id="copy">Copy SVG</button><button id="svg-export">SVG ↓</button><button class="primary" id="png-export">PNG ↓</button></div><p class="legal">Uses Lucide’s open-source icon set. Apple SF Symbols files are not bundled or redistributed.</p></section>`;
 bind();showFonts(); }
function showFonts(){const h=document.querySelector('header');if(!h)return;h.insertAdjacentHTML('afterend',`<div class="font-rack"><span>Authorized font sources</span><b class="font-google">&#xe000;&#xe01f;&#xe029;</b><b class="font-material">&#xe000;&#xe001;&#xe002;</b><b class="font-luminous">&#xe200;&#xe201;&#xe202;</b><b class="font-sf">&#xe001;&#xe002;&#xe003;</b><small>Google Symbols · Material Icons · Luminous · SF Symbols fallback</small></div>`)}
function download(type){ const markup=svg(selected,{width:size,height:size}); if(type==='svg'){ const blob=new Blob([markup],{type:'image/svg+xml'}); save(URL.createObjectURL(blob),'symbol-studio-'+selected+'.svg'); } else { const canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d');const image=new Image();image.onload=()=>{ctx.drawImage(image,0,0,size,size);save(canvas.toDataURL('image/png'),'symbol-studio-'+selected+'.png')};image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(markup); } }
function save(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),200)}
function bind(){ document.querySelectorAll('[data-cat]').forEach(e=>e.onclick=()=>{category=e.dataset.cat;render()});document.querySelectorAll('[data-symbol]').forEach(e=>e.onclick=()=>{selected=e.dataset.symbol;render()});document.querySelector('.search input').oninput=e=>{query=e.target.value;render()};document.querySelectorAll('[data-color]').forEach(e=>e.onclick=()=>{color=e.dataset.color;render()});document.querySelector('#picker').oninput=e=>{color=e.target.value;render()};document.querySelector('#stroke').oninput=e=>{stroke=e.target.value;render()};document.querySelector('#size').oninput=e=>{size=e.target.value;render()};document.querySelectorAll('[data-animation]').forEach(e=>e.onclick=()=>{animation=e.dataset.animation;render()});document.querySelector('#favorite').onclick=()=>{favorites=favorites.includes(selected)?favorites.filter(f=>f!==selected):[...favorites,selected];localStorage.setItem('symbol-studio-favorites',JSON.stringify(favorites));render()};document.querySelector('#random').onclick=()=>{selected=featured[Math.floor(Math.random()*featured.length)];render()};document.querySelector('#copy').onclick=async()=>{await navigator.clipboard.writeText(svg(selected,{width:size,height:size}));document.querySelector('#copy').textContent='Copied!';setTimeout(render,900)};document.querySelector('#svg-export').onclick=()=>download('svg');document.querySelector('#png-export').onclick=()=>download('png'); }
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('.search input')?.focus()}});render();
